<?php

namespace UserBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function ScorePlayer()
   {
       $qb = $this->createQueryBuilder('u');

       $qb->select('u.score')
           ->where('u.username = ?1')
           ->setParameters(array(1=> 'Player'))
          ;

       return $qb->getQuery()->getResult();
   }
}
